service:
  - docker
before_install:
  - cd $TRAVIS_BUILD_DIR
   - docker build . -t todo-app:test --target=test
   - docker run --name travisImage -d -p 5000:5000 -e key -e token todo-app:test
   - docker ps -a
  
 
