service:
  - docker
before_install:
   - docker build . -t todo-app:test 
   - docker run --name travisImage -d -p 5000:5000 -e key -e token --mount type=bind,source=$(pwd)/,target=/srv/www todo-app:test 
   - sleep 5
   - docker ps -a

script:  
- docker exec -it travisImage "pytest" --disable-pytest-warnings /srv/www/todo_app/tests
 
